import { Product, Category, Testimonial, Partner, Service, TeamMember, TimelineEvent, FAQ, NavLink, Stat, SuccessStory } from './types';

export const navLinks: NavLink[] = [
  { label: 'Home', href: '/' },
  {
    label: 'Products', href: '/products',
    children: [
      { label: 'Electronics', href: '/products?category=electronics' },
      { label: 'Machinery', href: '/products?category=machinery' },
      { label: 'Home & Living', href: '/products?category=home-living' },
      { label: 'Industrial Equipment', href: '/products?category=industrial' },
      { label: 'Consumer Goods', href: '/products?category=consumer' },
      { label: 'Wholesale', href: '/products?category=wholesale' },
    ]
  },
  { label: 'About', href: '/about' },
  { label: 'Services', href: '/services' },
  { label: 'Partners', href: '/partners' },
  { label: 'Contact', href: '/contact' },
];

export const stats: Stat[] = [
  { value: '50', suffix: '+', label: 'Countries Served' },
  { value: '10000', suffix: '+', label: 'Products Available' },
  { value: '500', suffix: '+', label: 'Global Partners' },
  { value: '98', suffix: '%', label: 'Client Satisfaction' },
];

export const categories: Category[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    description: 'Cutting-edge consumer and industrial electronics from verified manufacturers.',
    icon: 'Cpu',
    image: '/images/categories/electronics.jpg',
    productCount: 2400,
  },
  {
    id: 'machinery',
    name: 'Machinery',
    description: 'Heavy-duty machinery and precision equipment for industrial operations.',
    icon: 'Cog',
    image: '/images/categories/machinery.jpg',
    productCount: 1800,
  },
  {
    id: 'home-living',
    name: 'Home & Living',
    description: 'Premium home goods, furniture, and lifestyle products.',
    icon: 'Home',
    image: '/images/categories/home.jpg',
    productCount: 3200,
  },
  {
    id: 'industrial',
    name: 'Industrial Equipment',
    description: 'Industrial-grade tools, safety equipment, and facility supplies.',
    icon: 'Wrench',
    image: '/images/categories/industrial.jpg',
    productCount: 1500,
  },
  {
    id: 'consumer',
    name: 'Consumer Goods',
    description: 'Fast-moving consumer goods, fashion, and everyday essentials.',
    icon: 'ShoppingBag',
    image: '/images/categories/consumer.jpg',
    productCount: 4100,
  },
  {
    id: 'wholesale',
    name: 'Wholesale Products',
    description: 'Bulk supply solutions with competitive wholesale pricing.',
    icon: 'Package',
    image: '/images/categories/wholesale.jpg',
    productCount: 5600,
  },
];

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Smart Industrial IoT Sensor Module',
    category: 'electronics',
    description: 'Advanced IoT sensor module designed for industrial monitoring applications. Features real-time data transmission, multi-sensor integration (temperature, humidity, pressure), and industrial-grade durability. Compatible with major IoT platforms and supports MQTT, HTTP, and CoAP protocols.',
    shortDescription: 'Industrial-grade IoT sensor with real-time monitoring capabilities.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80'],
    moq: '100 Units',
    features: ['Multi-sensor integration', 'Real-time data transmission', 'Industrial-grade IP67 rating', 'Low power consumption', 'Wide protocol support'],
    specifications: { 'Operating Temperature': '-40°C to 85°C', 'Power Supply': '5V DC / PoE', 'Communication': 'WiFi / LoRa / 4G', 'Accuracy': '±0.5%', 'Dimensions': '80 x 50 x 30mm' },
    rating: 4.8,
    reviews: 127,
    badge: 'Best Seller',
    inStock: true,
  },
  {
    id: 'prod-002',
    name: 'CNC Precision Milling Machine XR-500',
    category: 'machinery',
    description: 'High-precision CNC milling machine with 5-axis capability. Designed for precision manufacturing in aerospace, automotive, and medical device industries. Features advanced servo motors, automatic tool changer, and intuitive touchscreen control system.',
    shortDescription: 'Professional 5-axis CNC milling machine for precision manufacturing.',
    image: 'https://images.unsplash.com/photo-1565439390111-54dfb5dbd0f0?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1565439390111-54dfb5dbd0f0?w=800&q=80'],
    moq: '1 Unit',
    features: ['5-axis machining', '24-tool automatic changer', 'Servo motor drive', '15" touchscreen control', 'CAD/CAM integration'],
    specifications: { 'Working Area': '500 x 400 x 300mm', 'Spindle Speed': '24,000 RPM', 'Positioning Accuracy': '±0.005mm', 'Power': '15kW', 'Weight': '3,200 kg' },
    rating: 4.9,
    reviews: 43,
    badge: 'Premium',
    inStock: true,
  },
  {
    id: 'prod-003',
    name: 'Premium Ceramic Dinner Set - 36 Piece',
    category: 'home-living',
    description: 'Exquisite 36-piece ceramic dinner set crafted from fine bone china. Features elegant gold-rimmed design with a timeless pattern. Includes dinner plates, salad plates, soup bowls, cups, and saucers. Dishwasher and microwave safe.',
    shortDescription: 'Elegant 36-piece bone china dinner set with gold accents.',
    image: 'https://images.unsplash.com/photo-1615800098779-1be32e60cca3?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1615800098779-1be32e60cca3?w=800&q=80'],
    moq: '50 Sets',
    features: ['Fine bone china', 'Gold-rimmed design', 'Dishwasher safe', 'Microwave safe', 'Chip-resistant'],
    specifications: { 'Material': 'Bone China', 'Pieces': '36', 'Dinner Plate': '27cm diameter', 'Finish': '24K gold trim', 'Packaging': 'Gift box' },
    rating: 4.7,
    reviews: 89,
    inStock: true,
  },
  {
    id: 'prod-004',
    name: 'Heavy Duty Hydraulic Press 200T',
    category: 'industrial',
    description: 'Industrial 200-ton hydraulic press suitable for metal forming, stamping, and deep drawing operations. Features programmable stroke control, safety light curtains, and dual-hand anti-tie-down controls for operator safety.',
    shortDescription: '200-ton hydraulic press for heavy industrial applications.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80'],
    moq: '1 Unit',
    features: ['200-ton capacity', 'Programmable stroke', 'Safety light curtains', 'Variable speed control', 'CE certified'],
    specifications: { 'Capacity': '200 Tons', 'Stroke': '400mm', 'Table Size': '800 x 600mm', 'Motor Power': '22kW', 'Safety': 'CE / ISO 13849' },
    rating: 4.6,
    reviews: 31,
    badge: 'Top Rated',
    inStock: true,
  },
  {
    id: 'prod-005',
    name: 'Wireless Bluetooth Earbuds Pro X3',
    category: 'consumer',
    description: 'Premium wireless earbuds with active noise cancellation, spatial audio support, and 36-hour total battery life. Features IPX5 water resistance, touch controls, and multipoint Bluetooth 5.3 connectivity.',
    shortDescription: 'Premium ANC wireless earbuds with spatial audio.',
    image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80'],
    moq: '500 Units',
    features: ['Active Noise Cancellation', 'Spatial Audio', '36hr battery life', 'IPX5 water resistance', 'Bluetooth 5.3'],
    specifications: { 'Driver': '11mm dynamic', 'Battery (buds)': '8 hours', 'Battery (case)': '28 hours', 'Charging': 'USB-C / Qi', 'Weight': '5.4g per earbud' },
    rating: 4.5,
    reviews: 342,
    badge: 'Hot',
    inStock: true,
  },
  {
    id: 'prod-006',
    name: 'LED Panel Light 600x600mm - Bulk Pack',
    category: 'wholesale',
    description: 'Commercial-grade LED panel lights ideal for offices, retail spaces, and warehouses. 40W output, 4000lm luminous flux, with flicker-free driver. Available in 3000K, 4000K, and 5000K color temperatures. 5-year warranty.',
    shortDescription: 'Commercial LED panels for wholesale distribution.',
    image: 'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=800&q=80'],
    moq: '200 Units',
    features: ['Flicker-free driver', '50,000hr lifespan', 'Multiple CCT options', 'UGR<19', '5-year warranty'],
    specifications: { 'Power': '40W', 'Luminous Flux': '4000lm', 'Color Temperature': '3000K/4000K/5000K', 'Size': '595 x 595 x 10mm', 'CRI': '>90' },
    rating: 4.4,
    reviews: 198,
    inStock: true,
  },
  {
    id: 'prod-007',
    name: 'Smart Home Security Camera System',
    category: 'electronics',
    description: 'Complete 8-channel smart security system with 4K cameras, AI-powered motion detection, and cloud storage integration. Features night vision up to 30m, two-way audio, and mobile app control.',
    shortDescription: '8-channel 4K smart security system with AI detection.',
    image: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=800&q=80'],
    moq: '20 Sets',
    features: ['4K resolution', 'AI motion detection', 'Night vision 30m', 'Two-way audio', 'Cloud + local storage'],
    specifications: { 'Resolution': '4K (8MP)', 'Channels': '8', 'Storage': '2TB HDD included', 'Night Vision': '30m IR', 'App': 'iOS / Android' },
    rating: 4.7,
    reviews: 156,
    badge: 'New',
    inStock: true,
  },
  {
    id: 'prod-008',
    name: 'Industrial Robot Arm 6-Axis RA-600',
    category: 'machinery',
    description: 'Versatile 6-axis articulated robot arm designed for assembly, welding, painting, and pick-and-place operations. Supports payload up to 6kg with ±0.02mm repeatability.',
    shortDescription: '6-axis industrial robot arm for automated manufacturing.',
    image: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800&q=80'],
    moq: '1 Unit',
    features: ['6-axis articulation', '6kg payload', '±0.02mm repeatability', 'Collaborative mode', 'Teach pendant included'],
    specifications: { 'Payload': '6kg', 'Reach': '900mm', 'Repeatability': '±0.02mm', 'Axes': '6', 'Weight': '52kg' },
    rating: 4.8,
    reviews: 28,
    badge: 'Premium',
    inStock: true,
  },
  {
    id: 'prod-009',
    name: 'Bamboo Fiber Bedding Set - King Size',
    category: 'home-living',
    description: 'Luxuriously soft bamboo fiber bedding set including duvet cover, flat sheet, and 4 pillowcases. Naturally hypoallergenic, moisture-wicking, and temperature regulating for superior sleep comfort.',
    shortDescription: 'Ultra-soft bamboo fiber king bedding set, hypoallergenic.',
    image: 'https://images.unsplash.com/photo-1522771731478-44bf1044086e?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1522771731478-44bf1044086e?w=800&q=80'],
    moq: '100 Sets',
    features: ['100% bamboo fiber', 'Hypoallergenic', 'Moisture-wicking', 'Temperature regulating', 'OEKO-TEX certified'],
    specifications: { 'Material': '100% Bamboo Viscose', 'Thread Count': '400TC', 'Size': 'King (260x240cm)', 'Pieces': '6', 'Care': 'Machine washable' },
    rating: 4.6,
    reviews: 74,
    inStock: true,
  },
  {
    id: 'prod-010',
    name: 'Solar Panel Module 550W Mono PERC',
    category: 'industrial',
    description: 'High-efficiency 550W monocrystalline PERC solar panel for commercial and utility-scale installations. Half-cut cell technology for improved shading tolerance and higher energy yield.',
    shortDescription: '550W high-efficiency mono PERC solar panel module.',
    image: 'https://images.unsplash.com/photo-1509391366360-12822a16d5ba?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1509391366360-12822a16d5ba?w=800&q=80'],
    moq: '50 Panels',
    features: ['Half-cut cell technology', '21.3% efficiency', 'PID resistant', '25-year warranty', 'TÜV certified'],
    specifications: { 'Power': '550W', 'Efficiency': '21.3%', 'Cells': '144 half-cut', 'Dimensions': '2279 x 1134 x 35mm', 'Weight': '28.6kg' },
    rating: 4.9,
    reviews: 212,
    badge: 'Top Rated',
    inStock: true,
  },
  {
    id: 'prod-011',
    name: 'Portable Bluetooth Speaker Waterproof',
    category: 'consumer',
    description: 'Rugged portable Bluetooth speaker with 360° surround sound, 24-hour battery life, and IP67 waterproof rating. Features built-in power bank, daisy-chain capability, and RGB light effects.',
    shortDescription: 'Waterproof portable speaker with 24hr battery life.',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80'],
    moq: '300 Units',
    features: ['360° surround sound', '24hr battery', 'IP67 waterproof', 'Built-in power bank', 'RGB light effects'],
    specifications: { 'Output': '30W', 'Battery': '24 hours', 'Waterproof': 'IP67', 'Bluetooth': '5.3', 'Weight': '720g' },
    rating: 4.3,
    reviews: 267,
    inStock: true,
  },
  {
    id: 'prod-012',
    name: 'Stainless Steel Kitchenware 20-Piece Set',
    category: 'wholesale',
    description: 'Professional-grade stainless steel kitchenware set including pots, pans, utensils, and accessories. Triple-ply construction with aluminum core for even heat distribution. Suitable for all cooktops including induction.',
    shortDescription: '20-piece professional stainless steel cookware set.',
    image: 'https://images.unsplash.com/photo-1584990347449-a6181b48bbd9?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1584990347449-a6181b48bbd9?w=800&q=80'],
    moq: '100 Sets',
    features: ['Triple-ply construction', 'Induction compatible', 'Oven safe to 260°C', 'Ergonomic handles', 'Lifetime warranty'],
    specifications: { 'Material': '18/10 Stainless Steel', 'Construction': 'Triple-ply', 'Pieces': '20', 'Cooktop': 'All types', 'Oven Safe': 'Up to 260°C' },
    rating: 4.5,
    reviews: 143,
    inStock: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-001',
    name: 'Michael Thompson',
    role: 'Procurement Director',
    company: 'TechVenture Inc.',
    country: 'United States',
    content: 'MK Trading has been our primary sourcing partner for over 5 years. Their quality control and logistics management are world-class. We\'ve reduced procurement costs by 35% while improving product quality.',
    avatar: '/images/avatars/avatar-1.jpg',
    rating: 5,
  },
  {
    id: 'test-002',
    name: 'Hans Mueller',
    role: 'Supply Chain Manager',
    company: 'EuroTech GmbH',
    country: 'Germany',
    content: 'The team at MK Trading understands the rigorous standards required for the European market. Their compliance documentation and product certifications are always impeccable.',
    avatar: '/images/avatars/avatar-2.jpg',
    rating: 5,
  },
  {
    id: 'test-003',
    name: 'Akiko Tanaka',
    role: 'CEO',
    company: 'Nihon Trading Co.',
    country: 'Japan',
    content: 'Exceptional service and reliability. MK Trading consistently delivers products that meet our exacting quality standards. Their multilingual support team makes communication effortless.',
    avatar: '/images/avatars/avatar-3.jpg',
    rating: 5,
  },
  {
    id: 'test-004',
    name: 'Carlos Rivera',
    role: 'Import Manager',
    company: 'Comercio Global SA',
    country: 'Brazil',
    content: 'Working with MK Trading has transformed our import operations. Their transparent pricing and reliable shipping timelines have made them an indispensable partner for our business.',
    avatar: '/images/avatars/avatar-4.jpg',
    rating: 4,
  },
  {
    id: 'test-005',
    name: 'Sarah Williams',
    role: 'Operations Director',
    company: 'Pacific Distributors',
    country: 'Australia',
    content: 'From initial inquiry to final delivery, MK Trading provides a seamless experience. Their product range is extensive and their pricing is consistently competitive.',
    avatar: '/images/avatars/avatar-5.jpg',
    rating: 5,
  },
];

export const partners: Partner[] = [
  { id: 'p1', name: 'TechVenture', logo: '/images/partners/partner-1.svg', country: 'USA' },
  { id: 'p2', name: 'EuroTech', logo: '/images/partners/partner-2.svg', country: 'Germany' },
  { id: 'p3', name: 'Nihon Trading', logo: '/images/partners/partner-3.svg', country: 'Japan' },
  { id: 'p4', name: 'Pacific Dist.', logo: '/images/partners/partner-4.svg', country: 'Australia' },
  { id: 'p5', name: 'Comercio Global', logo: '/images/partners/partner-5.svg', country: 'Brazil' },
  { id: 'p6', name: 'Nordic Supply', logo: '/images/partners/partner-6.svg', country: 'Sweden' },
  { id: 'p7', name: 'Gulf Traders', logo: '/images/partners/partner-7.svg', country: 'UAE' },
  { id: 'p8', name: 'AfriCommerce', logo: '/images/partners/partner-8.svg', country: 'South Africa' },
];

export const services: Service[] = [
  {
    id: 'svc-001',
    title: 'Product Sourcing',
    description: 'We leverage our extensive network of 500+ verified manufacturers to find the perfect products for your business. Our team negotiates the best prices while ensuring quality standards are met.',
    icon: 'Search',
    features: ['Manufacturer matching', 'Price negotiation', 'Sample coordination', 'Product development support'],
  },
  {
    id: 'svc-002',
    title: 'Quality Inspection',
    description: 'Rigorous quality control at every stage of production. Our QC team conducts pre-production, during-production, and pre-shipment inspections following AQL standards.',
    icon: 'ShieldCheck',
    features: ['AQL inspection', 'Factory audits', 'Lab testing', 'Defect analysis reports'],
  },
  {
    id: 'svc-003',
    title: 'Factory Audits',
    description: 'Comprehensive factory assessment covering production capabilities, quality management systems, social compliance, and environmental practices.',
    icon: 'ClipboardCheck',
    features: ['Capability assessment', 'ISO compliance check', 'Social audit', 'Environmental review'],
  },
  {
    id: 'svc-004',
    title: 'Global Logistics',
    description: 'End-to-end logistics management including freight forwarding, customs clearance, warehousing, and last-mile delivery across 50+ countries.',
    icon: 'Truck',
    features: ['Sea & air freight', 'Customs clearance', 'Warehousing', 'Door-to-door delivery'],
  },
  {
    id: 'svc-005',
    title: 'Procurement Solutions',
    description: 'Strategic procurement consulting and management services to optimize your supply chain, reduce costs, and improve efficiency.',
    icon: 'BarChart3',
    features: ['Cost optimization', 'Vendor management', 'Contract negotiation', 'Demand forecasting'],
  },
  {
    id: 'svc-006',
    title: 'Supply Chain Management',
    description: 'Full-spectrum supply chain management from raw materials to final delivery. Real-time tracking, inventory management, and performance analytics.',
    icon: 'Network',
    features: ['Real-time tracking', 'Inventory management', 'Risk mitigation', 'Performance analytics'],
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: 'team-001',
    name: 'David Chen',
    role: 'CEO & Founder',
    image: '/images/team/ceo.jpg',
    bio: 'With 25+ years in international trade, David founded MK Trading to bridge global markets with Chinese manufacturing excellence.',
  },
  {
    id: 'team-002',
    name: 'Li Wei',
    role: 'VP of Operations',
    image: '/images/team/vp-ops.jpg',
    bio: 'Former supply chain executive at a Fortune 500 company, Li leads our global operations with precision and efficiency.',
  },
  {
    id: 'team-003',
    name: 'Sarah Johnson',
    role: 'Head of International Sales',
    image: '/images/team/sales-head.jpg',
    bio: 'Sarah manages client relationships across 50+ countries, ensuring seamless communication and exceptional service delivery.',
  },
  {
    id: 'team-004',
    name: 'Zhang Ming',
    role: 'Director of Quality Assurance',
    image: '/images/team/qa-director.jpg',
    bio: 'Zhang oversees our rigorous quality control processes with ISO 9001 certification standards across all product lines.',
  },
];

export const timeline: TimelineEvent[] = [
  { year: '2003', title: 'Company Founded', description: 'MK Trading established in Guangzhou, China, starting with textile exports to Southeast Asia.' },
  { year: '2007', title: 'Electronics Division', description: 'Expanded into consumer electronics, partnering with 50+ Shenzhen manufacturers.' },
  { year: '2010', title: 'Global Expansion', description: 'Opened offices in Dubai, Hamburg, and Los Angeles to serve clients worldwide.' },
  { year: '2014', title: 'Industrial Products', description: 'Launched industrial equipment division, serving manufacturing clients across Europe.' },
  { year: '2018', title: 'Digital Transformation', description: 'Introduced digital procurement platform, streamlining orders for 300+ global clients.' },
  { year: '2021', title: 'Sustainability Initiative', description: 'Committed to carbon-neutral operations and eco-friendly product sourcing practices.' },
  { year: '2024', title: '10,000+ Products', description: 'Reached milestone of 10,000+ products across 6 major categories serving 50+ countries.' },
];

export const faqs: FAQ[] = [
  {
    question: 'What is the minimum order quantity (MOQ)?',
    answer: 'MOQ varies by product category. Consumer goods typically start at 100-500 units, while industrial equipment can be ordered individually. Contact our team for specific product MOQs.',
  },
  {
    question: 'How do you ensure product quality?',
    answer: 'We implement a rigorous 3-stage quality inspection process: pre-production, during-production, and pre-shipment. All inspections follow AQL 2.5 standards, and we provide detailed inspection reports with photos.',
  },
  {
    question: 'What payment methods do you accept?',
    answer: 'We accept T/T (bank transfer), L/C (letter of credit), PayPal for small orders, and offer trade assurance through major platforms. Typical terms are 30% deposit with 70% before shipment.',
  },
  {
    question: 'How long does shipping take?',
    answer: 'Sea freight typically takes 15-45 days depending on destination. Air freight takes 3-7 days. Express courier (DHL/FedEx) takes 3-5 days. We handle all customs documentation.',
  },
  {
    question: 'Can you provide product customization?',
    answer: 'Yes! We offer OEM and ODM services. Our partner factories can customize products with your branding, packaging, specifications, and design requirements. Minimum quantities apply.',
  },
  {
    question: 'Do you provide samples before ordering?',
    answer: 'Absolutely. We provide product samples for evaluation before placing bulk orders. Sample costs vary by product and are typically refundable upon order placement.',
  },
];

export const successStories: SuccessStory[] = [
  {
    id: 'ss-001',
    title: 'Scaling Electronics Distribution',
    company: 'TechVenture Inc.',
    country: 'United States',
    description: 'TechVenture partnered with MK Trading to source consumer electronics for their retail chain. Through our verified supplier network and quality control processes, they achieved remarkable growth.',
    results: ['35% cost reduction', '99.2% on-time delivery', '500K+ units shipped', '< 0.5% defect rate'],
    image: '/images/stories/techventure.jpg',
  },
  {
    id: 'ss-002',
    title: 'Industrial Equipment Procurement',
    company: 'EuroTech GmbH',
    country: 'Germany',
    description: 'EuroTech needed a reliable partner for sourcing industrial machinery meeting EU safety standards. MK Trading provided end-to-end procurement with full CE certification support.',
    results: ['28% procurement savings', 'Full CE compliance', '45+ machines delivered', 'Zero safety incidents'],
    image: '/images/stories/eurotech.jpg',
  },
  {
    id: 'ss-003',
    title: 'Home Goods Market Entry',
    company: 'Pacific Distributors',
    country: 'Australia',
    description: 'Pacific Distributors leveraged MK Trading\'s expertise to enter the premium home goods market. Our product development and sourcing capabilities enabled their successful market launch.',
    results: ['200+ SKUs launched', '$2M+ first year revenue', '4.7★ avg. product rating', '60% repeat orders'],
    image: '/images/stories/pacific.jpg',
  },
];
